### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [shibumi/bachelor-thesis#1]
Hello. Thanks for this repo and uploading your blackbox-exporter dashboard here: https://grafana.com/grafana/dashboards/9719

Would you be willing to post a LICENSE and perhaps NOTICE file on this repo to declare what license if any you want it to have?  Ideally for me, you would choose Apache 2.0. :-)

I won't be using your dashboard directly, but I did learn from your approach and would like to give you credit in my reimplementation of a small part of your dashboard. 

Thanks!

-Joshua

**Comment by shibumi** [comment]
Hi Joshua,
sorry for the late reply, I have been busy lately with my master.

I have added a MIT license file (this should be fine for commercial use). I hope this is fine. If you are unhappy with it, I am willing to change it to apache 2.0, but better you have a good reason for it :)

What do you mean with "NOTICE" file? What would you want in there?

**Comment by ghost** [comment]
MIT is good. thanks!
