### ISSUE TITLE
(dashboard) Variable refresh should be "On Time Series Change"

### ISSUE THREAD

**Issue by ghost** [shibumi/bachelor-thesis#2]
At the moment, the dashboard is broken out of the box. I couldn't get it to work until I changed variable refresh from "On Dashboard Load" to "On Time Series Change".

Thanks!

**Comment by shibumi** [comment]
Yes, that's an issue I ran into several times as well ( I still haven't changed my deployment and got used to just refreshing the time range and pressing F5.. lazy dev is lazy). Are you willing to send a patch for the dashboard.json file? Then I would upload the new file to grafana dashboards.

**Comment by shibumi** [comment]
Sorry for the late reply,
I have changed the variable `refresh` in the dashboard.json from `false` to `true`. I hope this fixes the issues.

**Comment by shibumi** [comment]
should be fixed with newest dashboard
